version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.0

jobs:
  build:
    docker:
      - image: 'circleci/node:10.13'
    working_directory: ~/ngrke
    steps:
      - checkout
      - restore_cache:
          keys:
          - ngrke-build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-build
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn build

  deploy_to_googlecloud:
    docker:
      - image: amitrke/node-appengine:latest
    working_directory: ~/ngrke
    steps:
      - checkout
      - restore_cache:
          keys:
          - ngrke-gcp-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-gcp
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-gcp-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn build
      - run:
          name: Dump Google Cloud Credentials to file
          command: echo ${GCLOUD_SERVICEACC_STORAGE} > ${HOME}/gcp-key.json
      - run:
          name: Active service account
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run:
          name: Set Google cloud project id
          command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Deploy to Google Cloud Storage
          command: gsutil -m rsync -d -r dist gs://${GOOGLE_STORAGE_BUCKET}
      - run:
          name: Set read access to files
          command: gsutil -m acl ch -r -u AllUsers:R gs://${GOOGLE_STORAGE_BUCKET}/*
  
  
  deploy_to_aws_dev:
    docker:
      - image: 'circleci/node:10.13'
    working_directory: ~/ngrke
    steps:
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - checkout
      - restore_cache:
          keys:
          - ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-aws
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn build
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - run:
          name: Deploy to S3 dev
          command: aws --region us-east-1 s3 sync dist s3://www-dev.aws.roorkee.org/ --delete

deploy_to_aws_prod:
    docker:
      - image: 'circleci/node:10.13'
    working_directory: ~/ngrke
    steps:
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - checkout
      - restore_cache:
          keys:
          - ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-aws
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn build
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - run:
          name: Deploy to S3 dev
          command: aws --region us-east-1 s3 sync dist s3://www.aws.roorkee.org/ --delete

workflows:
  google-master:
    jobs:
      - deploy_to_aws_prod:
          filters:
            branches:
              only: master
  aws-develop:
    jobs:
      - deploy_to_aws_dev:
          filters:
            branches:
              only: develop