version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.0

jobs:
  build:
    docker:
      - image: 'circleci/node:10.13'
    working_directory: ~/ngrke
    steps:
      - checkout
      - restore_cache:
          keys:
          - ngrke-build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-build
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn build

  deploy_to_aws_dev:
    docker:
      - image: 'circleci/node:10.13'
    working_directory: ~/ngrke
    steps:
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - checkout
      - run:
          name: Update Angular environment variables
          command: |
            echo ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
            ls -larth
            cat src/environments/environment.dev.ts
            sed -i "s/##WEBSITE##/rke-dev/g" src/environments/environment.dev.ts
            sed -i "s/##BUILD##/${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}/g" src/environments/environment.dev.ts
            cat src/environments/environment.dev.ts
      - restore_cache:
          keys:
          - ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-aws
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn run pubCache
      - run: yarn builddev
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - run:
          name: Deploy to S3 dev
          command: aws --region us-east-1 s3 sync dist s3://www-dev.aws.roorkee.org/ --delete

  deploy_to_aws_prod:
    docker:
      - image: 'circleci/node:10.13'
    working_directory: ~/ngrke
    steps:
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - checkout
      - run:
          name: Update Angular environment variables
          command: |
            echo ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
            ls -larth
            cat src/environments/environment.prod.ts
            sed -i "s/##WEBSITE##/rke-prod/g" src/environments/environment.prod.ts
            sed -i "s/##BUILD##/${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}/g" src/environments/environment.prod.ts
            cat src/environments/environment.prod.ts
      - restore_cache:
          keys:
          - ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - ngrke-aws
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: ngrke-aws-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
      - run: yarn run pubCache
      - run: yarn build
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - run:
          name: Deploy to S3 dev
          command: aws --region us-east-1 s3 sync dist s3://www.aws.roorkee.org/ --delete

workflows:
  google-master:
    jobs:
      - deploy_to_aws_prod:
          filters:
            branches:
              only: master
  aws-develop:
    jobs:
      - deploy_to_aws_dev:
          filters:
            branches:
              only: develop